### ISSUE TITLE
【建议】增加认证功能

### ISSUE THREAD

**Issue by winezer0** [jan-bar/UpDownFile#1]
建议增加认证功能，base头认证或者URL参数认证都可以。

防止被爬虫下载服务器敏感信息

**Comment by jan-bar** [comment]
类似`webdav`这种认证吧，`curl --user "username:password" http://xxx`，确实可以加上增加安全性。

**Comment by winezer0** [comment]
感谢认可，wait for you 。

**Comment by jan-bar** [comment]
安装最新代码：`go install github.com/jan-bar/UpDownFile@latest`

![image](https://github.com/jan-bar/UpDownFile/assets/14202095/d006ef60-86d7-4ef3-bae5-3902386a4b35)

浏览器也没问题，不过浏览器会记住认证信息，建议每次启动服务端都用不同的用户名密码。

你先测试看，有没有问题吧。

**Comment by winezer0** [comment]
wait my test

**Comment by winezer0** [comment]
![image](https://github.com/jan-bar/UpDownFile/assets/46115146/62f393d6-696f-4cab-950f-5c5bc185a480)

对于不存在的文件 会提示这些信息，建议修改为404 page

**Comment by winezer0** [comment]
![image](https://github.com/jan-bar/UpDownFile/assets/46115146/e2a2b7a3-d633-476e-baac-37a9d42df9cb)

测试中断上传 中断上传后 文件名已经保存在服务器了，不能继续上传，不清楚是不是预期的功能

![image](https://github.com/jan-bar/UpDownFile/assets/46115146/16dd87e4-514d-4537-b5f1-f42f07810842)

**Comment by jan-bar** [comment]
> 对于不存在的文件 会提示这些信息，建议修改为404 page

文件不存在时现在会返回404页面额。

> 测试中断上传 中断上传后 文件名已经保存在服务器了，不能继续上传，不清楚是不是预期的功能

这是个bug，当时太粗心额，也修复了。

**Comment by winezer0** [comment]
> 这是个bug，当时太粗心额，也修复了。

是现在修复的吗？我用的最新编译版本

**Comment by winezer0** [comment]
> 文件不存在时现在会返回404页面额。

好的，我测试测试

**Comment by jan-bar** [comment]
> 是现在修复的吗？我用的最新编译版本

刚才那个提交一起修复的额

**Comment by winezer0** [comment]
一个小bug

自动获取偏移量时
curl  -u "admin:adminaQQQWWW"  -C - -T example.zip http://xxxx56789/example.zip
返回的值是 
curl -C 47567752 -T file http://xxx:56789/example.zip

注意这个【file】没有被 example.zip 替代，这应该是非预期的


使用
curl  -u "admin:adminaQQQWWW"  -H "Content-Type:application/offset" http://xxxx:56789/example.zip
时，返回的值是 example.zip，这个是预期的
curl -C 49775282 -T example.zip http://xxxx:56789/example.zip

**Comment by winezer0** [comment]
认证功能+断点上传功能测试已正常运行。

**Comment by winezer0** [comment]
upDownFile cli -c 命令有点bug，好像不能-c ，

![image](https://github.com/jan-bar/UpDownFile/assets/46115146/2b3557b3-c49e-4305-b446-f19adf0ec211)

![image](https://github.com/jan-bar/UpDownFile/assets/46115146/184f077f-30b9-487f-ac06-0091a63e55a8)



后面加-c 可以运行，但是不会断点续传
![image](https://github.com/jan-bar/UpDownFile/assets/46115146/d94a2236-6c1c-43bf-a94a-3808700c2995)

**Comment by jan-bar** [comment]
我等会儿到家看看吧。

**Comment by winezer0** [comment]
ok wait

**Comment by jan-bar** [comment]
> upDownFile cli -c 命令有点bug，好像不能-c ，

你应该用了没有返回404那个版本，确实有bug。不过添加404文件不存在修改也恰好把这个修复了。

明确安装最新版：`go install github.com/jan-bar/UpDownFile@64c30f9`

获取偏移时返回文件名那个也修改好了，再测测看额。

最好执行`where upDownFile`看看你是不是用的旧代码的程序运行额。

**Comment by winezer0** [comment]
我是直接下载的master然后编译的，没有用go install哦。

我再试试看看

**Comment by jan-bar** [comment]
> 我是直接下载的master然后编译的，没有用go install哦。
> 
> 我再试试看看

嗯嗯，问题原因就是上传时，服务器文件不存在，之前我漏了测试断点上传。

**Comment by winezer0** [comment]
```
upDownFile cli -c -auth "admin:adminaQQQWWW" -d @example.zip "http://xxxxx:56789/example.zip"
strconv.ParseInt: parsing "": invalid syntax

```
![image](https://github.com/jan-bar/UpDownFile/assets/46115146/e4565765-480e-481e-9f6a-441db11af6aa)

```
upDownFile cli -c 10690984 -auth "admin:adminaQQQWWW" -d @example.zip "http://xxxx:56789/example.zip"
Get "10690984": unsupported protocol scheme ""
```

![image](https://github.com/jan-bar/UpDownFile/assets/46115146/91d33dfa-e7ef-4a80-b6e6-92fbad5237fc)


upDownFile cli -c 还是存在问题  可能是读取-c的参数值发生错误了？

**Comment by winezer0** [comment]
![image](https://github.com/jan-bar/UpDownFile/assets/46115146/81b9bd1d-bb44-4ee5-983f-8b9135313173)

代码是 20.53 的版本，下载时间是21.04

**Comment by jan-bar** [comment]
![GIF 2024-04-15-星期一 21-26-35](https://github.com/jan-bar/UpDownFile/assets/14202095/ab907833-0eef-4327-9c77-2c3fa68053de)

我这边测试没问题，你试试我上传的这个看看：[UpDownFile.zip](https://github.com/jan-bar/UpDownFile/files/14979632/UpDownFile.zip)

另外`-c`是布尔参数，不用携带数值额。

![image](https://github.com/jan-bar/UpDownFile/assets/14202095/3e60c514-b021-4316-87cd-ca7424d24380)

**Comment by winezer0** [comment]
奇了怪了，在我电脑上还是报错。使用cmd看看，我再看看

go 1.22.2

你发的我也运行不了，好像就没把-c作为一个bool识别

**Comment by jan-bar** [comment]
这个只能是上传时，服务器读文件失败，我只处理文件不存在的错误，你这可能是别的错误。我的代码还是有问题，出现错误不能返回http 200错误码。我再改改。

**Comment by winezer0** [comment]
我看了看，应该是parse int错误，估计是从服务器读取初始文件大小导致的。服务器初始文件大小应该是0

**Comment by winezer0** [comment]
打印错误看看了 发现是这个有错误 cur, err := fc.getServerFileSize(fc.httpUrl)

**Comment by jan-bar** [comment]
> 我看了看，应该是parse int错误，估计是从服务器读取初始文件大小导致的。服务器初始文件大小应该是0

我更新了代码，这次服务器有错误，客户端都会打印，我这边测试了服务器文件不存在和文件大小为0都没问题。你再试试看，我感觉可能是别的问题。例如文件夹没权限啥的，已经不是文件不存在的错误了。

**Comment by winezer0** [comment]
![image](https://github.com/jan-bar/UpDownFile/assets/46115146/424fc35a-e3d0-4c2e-bd91-721ff09727ca)


![image](https://github.com/jan-bar/UpDownFile/assets/46115146/aa2a60a6-b02c-4ad7-877d-b39461410a1f)

![image](https://github.com/jan-bar/UpDownFile/assets/46115146/68e71c4b-bdd4-4a49-b557-4c067d734118)

**Comment by winezer0** [comment]
加了一个测试代码，发现是 resp.Header.Get(offsetLength) == ""

每一次都需是重新上传，不知道服务器啥问题

**Comment by jan-bar** [comment]
> 加了一个测试代码，发现是 resp.Header.Get(offsetLength) == ""
> 
> 每一次都需是重新上传，不知道服务器啥问题

你服务器用的是最新代码的程序么？服务器需要文件不存在返回404那个改动额。

之前代码有判断`resp.StatusCode == http.StatusNotFound`表示服务器不存在文件

**Comment by winezer0** [comment]
我每次都是重新下载编译的

**Comment by jan-bar** [comment]
> 我每次都是重新下载编译的

你在服务端加个打印，目前只可能是这里出现错误，才会导致返回没有设置`offsetLength`额。

![image](https://github.com/jan-bar/UpDownFile/assets/14202095/7d97bf50-bb2b-427a-84e2-7d899ca2cc04)

**Comment by winezer0** [comment]
问题好像更严重了，我现在用 upDownFile cli -c  直接返回401

upDownFile cli -c  -auth "admin:123456" -d @example.zip http://xx:56789/example.zip
code:401,resp:Authenticate Error

 密钥是正常可用的

用 curl -u "admin:123456" -C - -T example.zip  "http://xxxx:56789/example.txt" 是正常的

**Comment by winezer0** [comment]
[test.zip](https://github.com/jan-bar/UpDownFile/files/14980631/test.zip)

这是我的go 1.22.2 编译版本

**Comment by winezer0** [comment]
![image](https://github.com/jan-bar/UpDownFile/assets/46115146/8d62ac74-0802-4887-921e-89c342e799a6)

看看 你那里是否正常吧，我放弃了，应该是我环境有问题。。。。

**Comment by jan-bar** [comment]
> 看看 你那里是否正常吧，我放弃了，应该是我环境有问题。

实在不好意思，是有bug。服务器带认证的时候，客户端断点上传这个http请求没有携带认证信息，怪我没有严格按照你的场景测试额。现在修改好了，你再试试吧。

这个项目没做好单元测试，等我有空补一补看看。

**Comment by winezer0** [comment]
重新测试了一下，这个版本应该是可以了，但是getServerFileSize 函数里面 认证头没有加上去，导致401。。。。

**Comment by jan-bar** [comment]
> 重新测试了一下，这个版本应该是可以了，但是getServerFileSize 函数里面 认证头没有加上去，导致401。。。。

嗯嗯，我加上了。现在应该没问题了额。

**Comment by winezer0** [comment]
![image](https://github.com/jan-bar/UpDownFile/assets/46115146/6f8fb82c-6c81-4271-bed6-898fe5617d58)

尴尬了 新的认证错误

**Comment by winezer0** [comment]
![image](https://github.com/jan-bar/UpDownFile/assets/46115146/a2458056-452b-4b89-b3fe-a963ea90f4a2)
并且 导致 现在无参数认证的断点也不可以使用了

**Comment by winezer0** [comment]
![image](https://github.com/jan-bar/UpDownFile/assets/46115146/ed394acc-8d4f-42d8-a061-e19ec58e57cc)

上一个版本简单修改加一句认证 fc.setBasicAuth(req) 就是可以用的，后面估计是改的太复杂了

**Comment by winezer0** [comment]
![image](https://github.com/jan-bar/UpDownFile/assets/46115146/41643f0d-8e2f-49c0-b2bb-e3d404c05859)

**Comment by winezer0** [comment]
服务端不能改成这个：
w.Header().Set(offsetLength, string(strconv.AppendInt(buf[:10], size, 10)))
改成这个会导致报错 line: Offset-Length:           66574403

**Comment by winezer0** [comment]
[UpDownFile-20240415.2323.zip](https://github.com/jan-bar/UpDownFile/files/14981100/UpDownFile-20240415.2323.zip)

测试可用代码，仅在上一版本的基础上，增加了一句认证头

**Comment by jan-bar** [comment]
这个size问题改了，那个认证授权的也改了。再测测看吧。我主要想把设置授权放到统一位置调用，我怕以后可能有相同重复逻辑，结果还改出新问题了。现在我把你上面列的都改了下，我这边自测还好。不清楚有没有别的啥问题额。

**Comment by winezer0** [comment]
稍等我看看

**Comment by winezer0** [comment]
OK 
DownFile cli 认证模式和非认证模式 断点下载测试通过
curl -C  -T 模式断点上传测试通过

![image](https://github.com/jan-bar/UpDownFile/assets/46115146/873b6bfd-23ee-4234-893f-6def62f31cfe)

**Comment by jan-bar** [comment]
> OK pDownFile cli 认证模式和非认证模式 断点下载测试通过

嗯嗯，可以睡觉了额。有问题，明天再解决哈。。早点睡觉咯。
