### ISSUE TITLE
【建议】希望能够增加参数隐藏目录浏览页面

### ISSUE THREAD

**Issue by winezer0** [jan-bar/UpDownFile#2]
1、希望能够增加参数隐藏目录浏览页面，在基本认证密钥泄漏的情况下，很容易泄漏所有文件。

**Comment by jan-bar** [comment]
`.\upDownFile -s :80 -deny` 增加参数，此时只允许请求文件，目录请求会拒绝额。

![image](https://github.com/jan-bar/UpDownFile/assets/14202095/53557c5c-e309-4563-a656-3d1e04c407a8)

**Comment by winezer0** [comment]
好的

**Comment by winezer0** [comment]
测试通过，没有问题
