### ISSUE TITLE
【建议】希望能够增加参数-log 记录请求日志

### ISSUE THREAD

**Issue by winezer0** [jan-bar/UpDownFile#3]
希望能够增加参数-log 记录请求日志  

为空时不记录，否则记录log【请求时间、请求IP、请求方法、完整URL等】到指定的目录或文件，提供追溯下载功能。

**Comment by jan-bar** [comment]
`.\upDownFile -s :8080 -log @log.txt`

使用日志模板，可以自定义日志格式，看看是不是你想要的功能。`http.Request`结构里面的字段你可以自由使用。

![image](https://github.com/jan-bar/UpDownFile/assets/14202095/62c2d113-fcfc-483b-b7b2-9709b31c349a)

**Comment by winezer0** [comment]
好的，感谢，学会了学会了

**Comment by winezer0** [comment]
-log功能是还没添加吗？

**Comment by winezer0** [comment]
最好就是能够自动配置日志文件大小，防止文件过大

**Comment by jan-bar** [comment]
> -log功能是还没添加吗？

这个功能是有了，没打包，你用最新代码编译吧。

> 最好就是能够自动配置日志文件大小，防止文件过大

我这项目自用都没想过长期运行，用完我就关了额。你这个是输出日志到文件，需要花点时间，还得测测进度条输出到文件是啥样的。空了我弄吧。

**Comment by winezer0** [comment]
不需要那么复杂，进度条信息可以忽略的。 
只需要简单请求记录就行
文件大小功能没有也不影响，定时清理一下就好了

**Comment by jan-bar** [comment]
> 不需要那么复杂，进度条信息可以忽略的。 只需要简单请求记录就行 文件大小功能没有也不影响，定时清理一下就好了

嗯嗯，我抽空补上吧。

**Comment by winezer0** [comment]
这个好像log.txt是指输出的格式，而不是输出的日志文件存储位置

**Comment by jan-bar** [comment]
> 这个好像log.txt是指输出的格式，而不是输出的日志文件存储位置

参数名称需要改改，现在参数越来越多了，我打算支持配置文件了，不然命令行太长了🤣。

**Comment by winezer0** [comment]
好的，有时间可以增加一下参数，配置文件模式可以等功能稳定了再发布

**Comment by jan-bar** [comment]
> 好的，有时间可以增加一下参数，配置文件模式可以等功能稳定了再发布

暂时用这两个参数控制日志输出吧：`.\upDownFile -s :8080 -logTpl @log.txt -log out.log`

代码更新了，你试试看😁。

**Comment by jan-bar** [comment]
现在支持大部分不常修改配置只能通过配置文件定义：https://github.com/jan-bar/UpDownFile/blob/master/server.yaml

支持2个可能经常修改的配置，命令行参数指定时会覆盖配置文件的定义

![image](https://github.com/jan-bar/UpDownFile/assets/14202095/d49e2110-7a14-4983-b3d9-accb07110541)

使用了一个日志库，支持按天数和按文件大小拆分日志文件，还能限定日志文件个数。如果有日志相关需求可以去这个日志库提issue额。

日志相关配置参考：https://github.com/natefinch/lumberjack?tab=readme-ov-file#type-logger

**Comment by winezer0** [comment]
好的，感谢，我晚点测试

**Comment by winezer0** [comment]
OK 没啥问题
