### ISSUE TITLE
【小bug】yaml配置文件中的path变量不基于相对变量

### ISSUE THREAD

**Issue by winezer0** [jan-bar/UpDownFile#4]
`./upDownFile.amd64 -c upDownFile.yaml  `
设置 path为 
```
path: ./webRoot/
path: webRoot/
path: webRoot
```

都没有办法访问 webRoot 内的 download目录文件.
![image](https://github.com/jan-bar/UpDownFile/assets/46115146/763c1db6-f194-4e98-8bd4-7a3c386ef18c)

`./upDownFile.amd64 -c upDownFile.yaml   -p  webRoot/ 是正常的
`
希望能在启动时输出当前的webRoot目录   支持相对路径

**Comment by jan-bar** [comment]
应该是这里默认值的问题

https://github.com/jan-bar/UpDownFile/blob/355a2058ebf82d5bcb281cfd75bf5503a0d94509/server.go#L31

会导致不用`-p xx`参数时，用不了配置文件里面的路径。

https://github.com/jan-bar/UpDownFile/blob/355a2058ebf82d5bcb281cfd75bf5503a0d94509/server.go#L65-L67

**Comment by jan-bar** [comment]
commit 里面带连接给关闭了 😅 。。你可以先测测，有问题再open吧。。

**Comment by winezer0** [comment]
测试通过 已修复
